Angular 17 (#76)
Downgrade from Angular 18 to 17

It doesn't seem like Firebase Hosting's experimental web framework support is ready for Angular 18 yet. When trying to deploy, I get the error:
```
Error: @angular-devkit/build-angular:application (open-ics:build:production) is not a recognized builder. Please check your angular.json
```

* Revert "Upgrade to Angular 18"

This reverts commit d5fb6fac211a5433a8b705caa78e70c021690ea3.

* Upgrade to latest minor versions

* Fix app providers